version: '3'
services:
  yasoucrawler:
    container_name: yasoucrawler
    image: "yasoucrawler:0.0.1"
    hostname: yasoucrawler.local
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8099:8099"
    networks:
      - deploy_meracrawler
    volumes:
      - ./.env:/app/.env

  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGODB_HOST=localhost
      - MONGODB_DBNAME=shopee
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "docker-healthcheck" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      deploy_meracrawler:
        ipv4_address: 172.16.238.12

networks:
  deploy_meracrawler:
    external: true
